version: "2.1"
services:
  app:
    build: ./app
    # restart: always
    depends_on:
      - server
    volumes:
      - .:/dished.-frontend/
    ports:
      - "3001:3001"

  server:
    build: ./server
    # restart: always
    volumes:
      - .:/dished.-backend/
    links:
      - redis:redis
    depends_on:
      - redis
    ports:
      - "5000:5000"

  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./data/redis:/var/lib/redisql/data
    ports:
      - "6379:6379"
