/**
 * All action types should be listed here
 */
module.exports = {
  // sign in
  SIGNIN_PENDING: 'SIGNIN_PENDING',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_FAILURE: 'SIGNIN_FAILURE',

  // sign up
  SIGNUP_PENDING: 'SIGNUP_PENDING',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',

  // edit user
  EDIT_USER_PENDING: 'EDIT_USER_PENDING',
  EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
  EDIT_USER_FAILURE: 'EDIT_USER_FAILURE',

  // start search process
  START_SEARCH_PROCESS: 'START_SEARCH_PROCESS',
  // location
  SUBMIT_LOCATION: 'SUBMIT_LOCATION',
  CONFIRM_LOCATION: 'CONFIRM_LOCATION',
  // transit
  SUBMIT_TRANSIT: 'SUBMIT_TRANSIT',
  // food
  SUBMIT_FOOD_TYPE: 'SUBMIT_FOOD_TYPE',
  // submit search
  SUBMIT_SEARCH_PENDING: 'SUBMIT_SEARCH_PENDING',
  SUBMIT_SEARCH_SUCCESS: 'SUBMIT_SEARCH_SUCCESS',
  SUBMIT_SEARCH_FAILURE: 'SUBMIT_SEARCH_FAILURE',
  // select choice
  SELECT_CHOICE_PENDING: 'SELECT_CHOICE_PENDING',
  SELECT_CHOICE_SUCCESS: 'SELECT_CHOICE_SUCCESS',
  SELECT_CHOICE_FAILURE: 'SELECT_CHOICE_FAILURE',
};
