/**
 * All action types should be listed here
 */
module.exports = {
  // sign in
  SIGN_IN_PENDING: 'SIGN_IN_PENDING',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

  // sign up
  SIGN_UP_PENDING: 'SIGN_UP_PENDING',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

  // sign out
  SIGN_OUT_PENDING: 'SIGN_OUT_PENDING',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',

  // edit user
  EDIT_USER_PENDING: 'EDIT_USER_PENDING',
  EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
  EDIT_USER_FAILURE: 'EDIT_USER_FAILURE',

  // start search process
  START_SEARCH_PROCESS: 'START_SEARCH_PROCESS',
  // location
  SUBMIT_LOCATION: 'SUBMIT_LOCATION',
  CONFIRM_LOCATION: 'CONFIRM_LOCATION',
  // transit
  SUBMIT_TRANSIT: 'SUBMIT_TRANSIT',
  // food
  SUBMIT_FOOD_TYPE: 'SUBMIT_FOOD_TYPE',
  // submit search
  SUBMIT_SEARCH_PENDING: 'SUBMIT_SEARCH_PENDING',
  SUBMIT_SEARCH_SUCCESS: 'SUBMIT_SEARCH_SUCCESS',
  SUBMIT_SEARCH_FAILURE: 'SUBMIT_SEARCH_FAILURE',
  // select choice
  SELECT_CHOICE_PENDING: 'SELECT_CHOICE_PENDING',
  SELECT_CHOICE_SUCCESS: 'SELECT_CHOICE_SUCCESS',
  SELECT_CHOICE_FAILURE: 'SELECT_CHOICE_FAILURE',
};
