/**
 * All action types should be listed here
 */
module.exports = {
  // sign in
  SIGN_IN_PENDING: 'SIGN_IN_PENDING',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
  // sign up
  SIGN_UP_PENDING: 'SIGN_UP_PENDING',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
  // sign out
  SIGN_OUT_PENDING: 'SIGN_OUT_PENDING',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
  // edit user
  EDIT_USER_PENDING: 'EDIT_USER_PENDING',
  EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
  EDIT_USER_FAILURE: 'EDIT_USER_FAILURE',
  // get user searches
  GET_USER_SEARCHES_PENDING: 'GET_USER_SEARCHES_PENDING',
  GET_USER_SEARCHES_SUCCESS: 'GET_USER_SEARCHES_SUCCESS',
  GET_USER_SEARCHES_FAILURE: 'GET_USER_SEARCHES_FAILURE',

  // change step
  CHANGE_STEP: 'CHANGE_STEP',
  // location
  SUBMIT_LOCATION: 'SUBMIT_LOCATION',
  CONFIRM_LOCATION: 'CONFIRM_LOCATION',
  // transit
  SUBMIT_TRANSIT_PENDING: 'SUBMIT_TRANSIT_PENDING',
  SUBMIT_TRANSIT_SUCCESS: 'SUBMIT_TRANSIT_SUCCESS',
  SUBMIT_TRANSIT_FAILURE: 'SUBMIT_TRANSIT_FAILURE',
  // food
  SUBMIT_FOOD_TYPE: 'SUBMIT_FOOD_TYPE',
  // submit search
  SUBMIT_SEARCH_PENDING: 'SUBMIT_SEARCH_PENDING',
  SUBMIT_SEARCH_SUCCESS: 'SUBMIT_SEARCH_SUCCESS',
  SUBMIT_SEARCH_FAILURE: 'SUBMIT_SEARCH_FAILURE',
  // select choice
  SELECT_CHOICE_PENDING: 'SELECT_CHOICE_PENDING',
  SELECT_CHOICE_SUCCESS: 'SELECT_CHOICE_SUCCESS',
  SELECT_CHOICE_FAILURE: 'SELECT_CHOICE_FAILURE',
  // mouse enter/leave choice
  MOUSE_ENTER_CHOICE: 'MOUSE_ENTER_CHOICE',
  MOUSE_LEAVE_CHOICE: 'MOUSE_LEAVE_CHOICE',
  // clear choices
  CLEAR_CHOICES: 'CLEAR_CHOICES',
  // clear search info
  CLEAR_SEARCH_INFO: 'CLEAR_SEARCH_INFO',

  // change modal
  CHANGE_MODAL: 'CHANGE_MODAL',
};
